import { FC, ReactNode } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface Props{
  children:ReactNode
}
export default function RootLayout({ children }:Props) {
  const menuItems = [
    {
      text: "Home",
      href: "/",
    },
    {
      text: "About",
      href: "/about",
    },
    {
      text: "Contact",
      href: "/contact",
    },
    {
      text: "Pricing",
      href: "/pricing",
    },
  ];
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <Navbar links={menuItems} />
        {children}
      </body>
    </html>
  );
}
